# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0004_auto_20160615_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niedzwiedz',
            fields=[
                ('pozycja_N', models.FloatField()),
                ('pozycja_E', models.FloatField()),
                ('identyfikator', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Nied\u017awiedzie',
            },
        ),
        migrations.AlterField(
            model_name='zagrozenieturysty',
            name='zagrozenie',
            field=models.CharField(choices=[('np', 'Mozliwe zaslabniecie, wyslij drona'), ('sz', 'Turysta w strefie zagrozenia'), ('oog', 'Turysta oddalil sie od lidera grupy'), ('n', 'Niedzwiedz blisko turysty')], max_length=255),
        ),
    ]
