# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 11:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deszcz',
            options={'verbose_name_plural': 'Stopnie deszczu'},
        ),
        migrations.AlterModelOptions(
            name='lawina',
            options={'verbose_name_plural': 'Stopnie lawiny'},
        ),
        migrations.AlterModelOptions(
            name='mgla',
            options={'verbose_name_plural': 'Stopnie mg\u0142y'},
        ),
        migrations.AlterModelOptions(
            name='pogoda',
            options={'verbose_name_plural': 'Pogody'},
        ),
        migrations.AlterModelOptions(
            name='stanalarmowy',
            options={'verbose_name_plural': 'Stany alarmowe'},
        ),
        migrations.AlterModelOptions(
            name='szlak',
            options={'verbose_name_plural': 'Szlaki'},
        ),
        migrations.AlterModelOptions(
            name='temperatura',
            options={'verbose_name_plural': 'Stopnie temperatury'},
        ),
        migrations.AlterModelOptions(
            name='wiatr',
            options={'verbose_name_plural': 'Stopnie wiatru'},
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='maksymalna_dodatnia',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='maksymalna_ujemna',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='minimalna_dodatnia',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='minimalna_ujemna',
        ),
        migrations.AddField(
            model_name='temperatura',
            name='ponizej',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='powyzej',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deszcz',
            name='deszcz_maksymalny',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deszcz',
            name='deszcz_minimalny',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deszcz',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lawina',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mgla',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stanalarmowy',
            name='poziom',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='szlak',
            name='trudnosc',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wiatr',
            name='predkosc_maksymalna',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wiatr',
            name='predkosc_minimalna',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wiatr',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
