# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 12:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_auto_20160521_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='szlak',
            name='nazwa',
            field=models.CharField(default='brak', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deszcz',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lawina',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mgla',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stanalarmowy',
            name='poziom',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wiatr',
            name='stopien',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
