# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_auto_20160521_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szlak',
            name='pogoda',
        ),
        migrations.AddField(
            model_name='pogoda',
            name='szlak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_app.Szlak'),
        ),
    ]
