# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0005_strefazagrozenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strefazagrozenia',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='strefazagrozenia',
            name='srednica',
            field=models.IntegerField(help_text='jednostka [m]'),
        ),
        migrations.AlterField(
            model_name='strefazagrozenia',
            name='srodek',
            field=models.TextField(),
        ),
    ]
