# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0006_auto_20160620_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strefazagrozenia',
            name='srodek',
        ),
        migrations.AddField(
            model_name='strefazagrozenia',
            name='pozycja_E',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strefazagrozenia',
            name='pozycja_N',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
