# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0007_auto_20160620_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strefazagrozenia',
            old_name='srednica',
            new_name='promien',
        ),
    ]
